import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Project, AnalysisResult } from '../types';

// --- Types ---


// --- Helper Functions ---

const formatDate = (date: Date | string) => {
    return new Date(date).toLocaleString();
};

const addHeader = (doc: jsPDF, title: string, subtitle?: string) => {
    const pageWidth = doc.internal.pageSize.width;

    // Logo / Brand
    doc.setFontSize(24);
    doc.setTextColor(79, 70, 229); // Primary-600 (Indigo)
    doc.setFont('helvetica', 'bold');
    doc.text('TrustAI', 20, 20);

    // Title
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59); // Slate-800
    doc.setFont('helvetica', 'bold');
    doc.text(title, 20, 35);

    // Subtitle
    if (subtitle) {
        doc.setFontSize(12);
        doc.setTextColor(100, 116, 139); // Slate-500
        doc.setFont('helvetica', 'normal');
        doc.text(subtitle, 20, 42);
    }

    // Line separator
    doc.setDrawColor(226, 232, 240); // Slate-200
    doc.line(20, 48, pageWidth - 20, 48);

    return 55; // Return Y position for next content
};

const addFooter = (doc: jsPDF) => {
    const pageCount = doc.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate-400
        doc.text(
            `Generated by TrustAI on ${new Date().toLocaleString()}`,
            20,
            pageHeight - 10
        );
        doc.text(
            `Page ${i} of ${pageCount}`,
            pageWidth - 30,
            pageHeight - 10
        );
    }
};

const getTrustColor = (score: number) => {
    if (score >= 80) return [34, 197, 94]; // Green-500
    if (score >= 50) return [234, 179, 8]; // Yellow-500
    return [239, 68, 68]; // Red-500
};

// --- Export Functions ---

export const downloadJSON = (data: any, fileName: string) => {
    const jsonString = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileName}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

export const downloadMarkdown = (content: string, fileName: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileName}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

export const downloadAnalysisPDF = (analysis: AnalysisResult, project?: Project) => {
    const doc = new jsPDF();
    let y = addHeader(doc, 'Analysis Report', project ? `Project: ${project.name}` : 'Single Analysis');

    // Meta Info
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Analysis ID: ${analysis.id}`, 20, y);
    doc.text(`Date: ${formatDate(analysis.timestamp)}`, 120, y);
    y += 10;

    if (analysis.fileName) {
        doc.text(`Source File: ${analysis.fileName}`, 20, y);
        doc.text(`Type: ${analysis.type}`, 120, y);
        y += 10;
    }

    // Trust Score Section
    y += 5;
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.roundedRect(20, y, 170, 25, 3, 3, 'F');

    doc.setFontSize(12);
    doc.setTextColor(70);
    doc.text('Trust Score', 30, y + 16);

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    const color = getTrustColor(analysis.trustScore);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(`${analysis.trustScore}/100`, 80, y + 16);

    doc.setFontSize(14);
    doc.text(analysis.status || 'Neutral', 140, y + 16);

    y += 35;

    // Content Section
    doc.setFontSize(14);
    doc.setTextColor(30);
    doc.setFont('helvetica', 'bold');
    doc.text('Analysis Result', 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setTextColor(50);
    doc.setFont('helvetica', 'normal');

    const splitText = doc.splitTextToSize(analysis.aiResponse, 170);
    doc.text(splitText, 20, y);
    y += splitText.length * 5 + 10;

    // Input Content (if available)
    if (analysis.content) {
        if (y > 250) { doc.addPage(); y = 20; }

        doc.setFontSize(14);
        doc.setTextColor(30);
        doc.setFont('helvetica', 'bold');
        doc.text('Input Content', 20, y);
        y += 10;

        doc.setFontSize(10);
        doc.setTextColor(80);
        doc.setFont('helvetica', 'normal');

        const splitInput = doc.splitTextToSize(analysis.content, 170);
        doc.text(splitInput, 20, y);
    }

    addFooter(doc);
    doc.save(`Analysis_Report_${analysis.id}.pdf`);
};

export const downloadProjectPDF = (project: Project) => {
    const doc = new jsPDF();
    let y = addHeader(doc, 'Project Report', project.name);

    // Project Overview
    autoTable(doc, {
        startY: y,
        head: [['Metric', 'Value']],
        body: [
            ['Project Name', project.name],
            ['Category', project.category],
            ['Status', project.status],
            ['Trust Score', `${project.trustScore}/100`],
            ['Total Files', project.files.toString()],
            ['Total Analyses', project.history.length.toString()],
            ['Last Updated', formatDate(project.lastUpdated)],
            ['Created', formatDate(project.created)],
        ],
        theme: 'striped',
        headStyles: { fillColor: [79, 70, 229] },
        margin: { top: 10 }
    });

    y = (doc as any).lastAutoTable.finalY + 15;

    // Analyses History
    doc.setFontSize(14);
    doc.setTextColor(30);
    doc.setFont('helvetica', 'bold');
    doc.text('Analysis History', 20, y);
    y += 5;

    const historyData = project.history.map(h => [
        formatDate(h.timestamp),
        h.fileName || 'Text Input',
        h.type,
        `${h.trustScore}/100`,
        h.status
    ]);

    autoTable(doc, {
        startY: y,
        head: [['Date', 'Source', 'Type', 'Score', 'Status']],
        body: historyData,
        theme: 'grid',
        headStyles: { fillColor: [100, 116, 139] },
    });

    // Detailed Analyses (New Pages)
    project.history.forEach((analysis, index) => {
        doc.addPage();
        let py = 20;

        doc.setFontSize(16);
        doc.setTextColor(30);
        doc.setFont('helvetica', 'bold');
        doc.text(`Analysis #${index + 1}`, 20, py);
        py += 10;

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`ID: ${analysis.id} | Date: ${formatDate(analysis.timestamp)}`, 20, py);
        py += 15;

        // Score Box
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(20, py, 170, 20, 2, 2, 'F');
        doc.setFontSize(12);
        doc.setTextColor(30);
        doc.text(`Score: ${analysis.trustScore}/100  -  ${analysis.status}`, 30, py + 13);
        py += 30;

        // AI Response
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('AI Findings:', 20, py);
        py += 8;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(50);
        const splitRes = doc.splitTextToSize(analysis.aiResponse, 170);
        doc.text(splitRes, 20, py);
    });

    addFooter(doc);
    doc.save(`${project.name.replace(/\s+/g, '_')}_Report.pdf`);
};
